apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-stress-checkout
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
      - online-boutique
    labelSelectors:
      app: checkoutservice
  stressors:
    memory:
      workers: 1
      size: "200M"
  duration: "5m"

