// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: rating.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRatingRequest) Reset() {
	*x = SubmitRatingRequest{}
	mi := &file_rating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRatingRequest) ProtoMessage() {}

func (x *SubmitRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRatingRequest.ProtoReflect.Descriptor instead.
func (*SubmitRatingRequest) Descriptor() ([]byte, []int) {
	return file_rating_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitRatingRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SubmitRatingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitRatingRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitRatingRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SubmitRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRatingResponse) Reset() {
	*x = SubmitRatingResponse{}
	mi := &file_rating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRatingResponse) ProtoMessage() {}

func (x *SubmitRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRatingResponse.ProtoReflect.Descriptor instead.
func (*SubmitRatingResponse) Descriptor() ([]byte, []int) {
	return file_rating_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitRatingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitRatingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProductRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRatingRequest) Reset() {
	*x = GetProductRatingRequest{}
	mi := &file_rating_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRatingRequest) ProtoMessage() {}

func (x *GetProductRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRatingRequest.ProtoReflect.Descriptor instead.
func (*GetProductRatingRequest) Descriptor() ([]byte, []int) {
	return file_rating_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductRatingRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetProductRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AverageScore  float32                `protobuf:"fixed32,2,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"`
	TotalRatings  int32                  `protobuf:"varint,3,opt,name=total_ratings,json=totalRatings,proto3" json:"total_ratings,omitempty"`
	Ratings       []*Rating              `protobuf:"bytes,4,rep,name=ratings,proto3" json:"ratings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRatingResponse) Reset() {
	*x = GetProductRatingResponse{}
	mi := &file_rating_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRatingResponse) ProtoMessage() {}

func (x *GetProductRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRatingResponse.ProtoReflect.Descriptor instead.
func (*GetProductRatingResponse) Descriptor() ([]byte, []int) {
	return file_rating_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductRatingResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetProductRatingResponse) GetAverageScore() float32 {
	if x != nil {
		return x.AverageScore
	}
	return 0
}

func (x *GetProductRatingResponse) GetTotalRatings() int32 {
	if x != nil {
		return x.TotalRatings
	}
	return 0
}

func (x *GetProductRatingResponse) GetRatings() []*Rating {
	if x != nil {
		return x.Ratings
	}
	return nil
}

type GetUserRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRatingRequest) Reset() {
	*x = GetUserRatingRequest{}
	mi := &file_rating_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRatingRequest) ProtoMessage() {}

func (x *GetUserRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rating_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRatingRequest.ProtoReflect.Descriptor instead.
func (*GetUserRatingRequest) Descriptor() ([]byte, []int) {
	return file_rating_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRatingRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetUserRatingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        *Rating                `protobuf:"bytes,1,opt,name=rating,proto3" json:"rating,omitempty"`
	HasRating     bool                   `protobuf:"varint,2,opt,name=has_rating,json=hasRating,proto3" json:"has_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRatingResponse) Reset() {
	*x = GetUserRatingResponse{}
	mi := &file_rating_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRatingResponse) ProtoMessage() {}

func (x *GetUserRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rating_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRatingResponse.ProtoReflect.Descriptor instead.
func (*GetUserRatingResponse) Descriptor() ([]byte, []int) {
	return file_rating_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRatingResponse) GetRating() *Rating {
	if x != nil {
		return x.Rating
	}
	return nil
}

func (x *GetUserRatingResponse) GetHasRating() bool {
	if x != nil {
		return x.HasRating
	}
	return false
}

type Rating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rating) Reset() {
	*x = Rating{}
	mi := &file_rating_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_rating_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_rating_proto_rawDescGZIP(), []int{6}
}

func (x *Rating) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Rating) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Rating) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Rating) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Rating) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_rating_proto protoreflect.FileDescriptor

const file_rating_proto_rawDesc = "" +
	"\n" +
	"\frating.proto\x12\vhipstershop\"}\n" +
	"\x13SubmitRatingRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"J\n" +
	"\x14SubmitRatingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x17GetProductRatingRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\xb2\x01\n" +
	"\x18GetProductRatingResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\raverage_score\x18\x02 \x01(\x02R\faverageScore\x12#\n" +
	"\rtotal_ratings\x18\x03 \x01(\x05R\ftotalRatings\x12-\n" +
	"\aratings\x18\x04 \x03(\v2\x13.hipstershop.RatingR\aratings\"N\n" +
	"\x14GetUserRatingRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"c\n" +
	"\x15GetUserRatingResponse\x12+\n" +
	"\x06rating\x18\x01 \x01(\v2\x13.hipstershop.RatingR\x06rating\x12\x1d\n" +
	"\n" +
	"has_rating\x18\x02 \x01(\bR\thasRating\"\x8e\x01\n" +
	"\x06Rating\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp2\x9d\x02\n" +
	"\rRatingService\x12S\n" +
	"\fSubmitRating\x12 .hipstershop.SubmitRatingRequest\x1a!.hipstershop.SubmitRatingResponse\x12_\n" +
	"\x10GetProductRating\x12$.hipstershop.GetProductRatingRequest\x1a%.hipstershop.GetProductRatingResponse\x12V\n" +
	"\rGetUserRating\x12!.hipstershop.GetUserRatingRequest\x1a\".hipstershop.GetUserRatingResponseBNZLgithub.com/GoogleCloudPlatform/microservices-demo/src/ratingservice/genprotob\x06proto3"

var (
	file_rating_proto_rawDescOnce sync.Once
	file_rating_proto_rawDescData []byte
)

func file_rating_proto_rawDescGZIP() []byte {
	file_rating_proto_rawDescOnce.Do(func() {
		file_rating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rating_proto_rawDesc), len(file_rating_proto_rawDesc)))
	})
	return file_rating_proto_rawDescData
}

var file_rating_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rating_proto_goTypes = []any{
	(*SubmitRatingRequest)(nil),      // 0: hipstershop.SubmitRatingRequest
	(*SubmitRatingResponse)(nil),     // 1: hipstershop.SubmitRatingResponse
	(*GetProductRatingRequest)(nil),  // 2: hipstershop.GetProductRatingRequest
	(*GetProductRatingResponse)(nil), // 3: hipstershop.GetProductRatingResponse
	(*GetUserRatingRequest)(nil),     // 4: hipstershop.GetUserRatingRequest
	(*GetUserRatingResponse)(nil),    // 5: hipstershop.GetUserRatingResponse
	(*Rating)(nil),                   // 6: hipstershop.Rating
}
var file_rating_proto_depIdxs = []int32{
	6, // 0: hipstershop.GetProductRatingResponse.ratings:type_name -> hipstershop.Rating
	6, // 1: hipstershop.GetUserRatingResponse.rating:type_name -> hipstershop.Rating
	0, // 2: hipstershop.RatingService.SubmitRating:input_type -> hipstershop.SubmitRatingRequest
	2, // 3: hipstershop.RatingService.GetProductRating:input_type -> hipstershop.GetProductRatingRequest
	4, // 4: hipstershop.RatingService.GetUserRating:input_type -> hipstershop.GetUserRatingRequest
	1, // 5: hipstershop.RatingService.SubmitRating:output_type -> hipstershop.SubmitRatingResponse
	3, // 6: hipstershop.RatingService.GetProductRating:output_type -> hipstershop.GetProductRatingResponse
	5, // 7: hipstershop.RatingService.GetUserRating:output_type -> hipstershop.GetUserRatingResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rating_proto_init() }
func file_rating_proto_init() {
	if File_rating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rating_proto_rawDesc), len(file_rating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rating_proto_goTypes,
		DependencyIndexes: file_rating_proto_depIdxs,
		MessageInfos:      file_rating_proto_msgTypes,
	}.Build()
	File_rating_proto = out.File
	file_rating_proto_goTypes = nil
	file_rating_proto_depIdxs = nil
}
