apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratingservice
spec:
  selector:
    matchLabels:
      app: ratingservice
  template:
    metadata:
      labels:
        app: ratingservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: gcr.io/google-samples/microservices-demo/ratingservice:v0.10.1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: 8080
        livenessProbe:
          grpc:
            port: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ratingservice
spec:
  type: ClusterIP
  selector:
    app: ratingservice
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080